server:
  port: 8080

spring:
  application:
    name: api-service
  cloud:
    gateway:
      routes:
        - id: security-service
          uri: lb://SECURITY-SERVICE
          predicates:
            - Path=/api/v1/auth/**
        - id: security-service-docs
          uri: lb://SECURITY-SERVICE
          predicates:
            - Path=/security-service/api-docs/**

        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - Authentication
        - id: message-service-docs
          uri: lb://message-service
          predicates:
            - Path=/message-service/api-docs/**

        - id: templates
          uri: lb://TEMPLATES
          predicates:
            - Path=/api/v1/templates/**
          filters:
            - Authentication
        - id: templates-docs
          uri: lb://TEMPLATES
          predicates:
            - Path=/templates/api-docs/**

        - id: recipient
          uri: lb://recipient
          predicates:
            - Path=/api/v1/recipients/**
          filters:
            - Authentication
        - id: recipient-docs
          uri: lb://recipient
          predicates:
            - Path=/recipient/api-docs/**

        - id: file-service
          uri: lb://FILE-SERVICE
          predicates:
            - Path=/api/v1/files/**
          filters:
            - Authentication
        - id: file-service-docs
          uri: lb://FILE-SERVICE
          predicates:
            - Path=/file-service/api-docs/**

        - id: link-shortener
          uri: lb://LINK-SHORTENER
          predicates:
            - Path=/api/v1/responses/**
        - id: link-shortener-docs
          uri: lb://LINK-SHORTENER
          predicates:
            - Path=/link-shortener/api-docs/**

# http://localhost:8080/webjars/swagger-ui/index.html
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    url: http://localhost:8080/v3/api-docs
    urls:
      - name: message-service
        url: /message-service/api-docs
      - name: message-service
        url: /security-service/api-docs
      - name: templates
        url: /templates/api-docs
      - name: recipient
        url: /recipient/api-docs
      - name: file-service
        url: /file-service/api-docs
      - name: link-shortener
        url: /link-shortener/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

urls:
  validate: http://localhost:8080/api/v1/auth/validate