server:
  port: 0

spring:
  application:
    name: recipient
  datasource:
    username: user
    password: 1234567890
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/recipient
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    partitions: 3
    topics:
      recipient-update: recipient-updated
      template-update: template-updated

springdoc:
  api-docs:
    path: /recipient/api-docs

logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate: ERROR
    com:
      example:
        recipient: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 1
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}