server:
  port: 0

spring:
  application:
    name: rebalancer
  kafka:
    bootstrap-servers: localhost:9092
    topics:
      notifications:
        email: email - topic
        phone: phone - topic
        telegram: telegram - topic

rebroadcaster:
  pending-threshold: 5
  new-threshold: 5
  fetch-limit: 15

services:
  notification: message-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 1
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}